services:
  - type: web
    name: attendance-app
    env: node
    plan: free
    buildCommand: "npm install && cd frontend && npm install && npm run build"
    startCommand: "node backend/server.js"
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: MAIL_USER
        sync: false
      - key: MAIL_PASS
        sync: false
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
